name: password_generator_quoclewkm
description: A library for generating random passwords.
version: 1.0.0
repository: https://github.com/quoclewkm/password_generator
homepage: https://pub.dev

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
